### ISSUE TITLE
JS loading and syntax highlighting

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#31]
I was just looking at this page:

https://vatlab.github.io/sos-docs/doc/documentation/SoS_Syntax.html#Comments-and-help-message-18

Problems:

1. Loading the code box takes quite a while (a couple of seconds) on my computer
2. and when loaded, the `report` action has improperly displayed Rmd content for `#`. 

I've never seen 1 before.

For 2, I think this problem has once been resolved? Is it because I somehow failed to update something on my computer when I rebuilt all documentation pages -- I did rebuilt them all yesterday to release some changes I made on manuscript example page.

Do you have a thought on this, or maybe it helps to verify if you force build every page?

**Comment by BoPeng** [comment]
For 1, the problem is with the highlighting, which is done sequentially from the top. When you open the page from the top, the cells are still rendering but you will not notice it. It is a different story when you jump to the middle of the page.

I will have to know the platform to confirm, notebook or lab? As far as I can tell, both were fixed.

**Comment by BoPeng** [comment]
There is one thing we can do for 1 though. That is to say, we apply appropriate css to the textarea so that it will appear normal without syntax highligting. Then the effect of codemirror would be just changing the color of exisitng text.

**Comment by BoPeng** [comment]
It is surprisingly a lot of work to fix this, but the loading should be a lot better now.

**Comment by gaow** [comment]
Yes it is a lot better than before!
