### ISSUE TITLE
Live serve not alive

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#64]
![2019-02-22-11-59-13_scrot](https://user-images.githubusercontent.com/917985/53261346-60984980-3699-11e9-9675-1cfeeffef842.png)

**Comment by BoPeng** [comment]
Works for me right now.

I think I set the number to 25, but the problem is that dockerhub does not kill instances automatically so  the number accumulates. There is [a script to kill idle workers](https://github.com/jupyterhub/jupyterhub/blob/master/examples/cull-idle/cull_idle_servers.py) but it did not work for me, perhaps I did not try hard enough.

**Comment by BoPeng** [comment]
The script is [here](https://github.com/vatlab/sos-docs/tree/master/development/jupyterhub/docker-jupyterhub). I cited it [here](https://github.com/vatlab/sos-docs/blob/master/development/jupyterhub/docker-jupyterhub/jupyterhub_config.py#L33) but it did not work.

Ohmm, perhaps the script should be copied to the docker image [like the config file] (https://github.com/vatlab/sos-docs/blob/master/development/jupyterhub/docker-jupyterhub/Dockerfile#L4)? Let me try.

**Comment by BoPeng** [comment]
https://github.com/vatlab/sos-docs/commit/4343a351f10afe66569a8f56d789b0a0e630d1b5

OK, missed a `import sys` since the configuration file uses `sys.executable`.  The server is up and running again now, and hopefully the script would help killing server instances.

**Comment by gaow** [comment]
Looks like yes! I'll close it for now.
